import 'package:lite_graphql/lite_graphql.dart';

Future<void> main() async {
  // Configure the GraphQL lite client
  String url = "https://api.lnmetrics.info/query";
  var client = GraphQLClient(baseUrl: url);
  // This can be autogenerated
  client.addQuery("QUERY_LIST_NODES", """
    query {
       getNodes(network: "bitcoin") {
          alias
          node_id
        }
    }
  """);
  var listNodes = await client.useQuery(key: "QUERY_LIST_NODES");
  print('Result is: ${listNodes.toString()}');
}
