name: lite_graphql
description: A light way implementation of GraphQL client in dart language.
version: 0.0.1
homepage: https://github.com/vincenzopalazzo/lite-graphql

false_secrets:
  - /credentials.json

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  http: ^0.13.4
  logger: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
